MODULE_NAME=mchw_riscv
obj-m += $(MODULE_NAME).o 
PMCSCHED-objs= pmcsched.o dummy_plugin.o group_plugin.o	busybcs_plugin.o
$(MODULE_NAME)-objs +=  mchw_core.o mc_experiments.o pmu_config_perf.o cbuffer.o monitoring_mod.o syswide.o  pmctrack_stub.o $(PMCSCHED-objs)
USER_CFLAGS ?=
#USER_CFLAGS ?= -ggdb -O0
EXTRA_CFLAGS += $(USER_CFLAGS) -DCONFIG_PMC_PERF -I$(src)/../include -I$(src)/..
